export var listaClientes = {
  ZSYL: {
    nome: 'Carolaine',
    cidade: '',
    celular: '',
    quem_convidou: '',
    obs: '',
    classificacao: 'cliente',
  },
  ZSYU: {
    nome: 'Cliente',
    cidade: '',
    celular: '',
    quem_convidou: '',
    obs: '',
    classificacao: 'cliente',
  },
  ZSYT: {
    nome: 'Elton Farley',
    cidade: 'São Pedro da Aldeia',
    celular: 22988215222,
    quem_convidou: 'Márcio',
    obs: 'Cliente que fez a conecção toyoserra e prefeito Fábio',
    classificacao: 'cliente',
  },
  XCNH: {
    nome: 'Monike Azevedo',
    cidade: 'São Pedro da Aldeia',
    celular: 22999112048,
    quem_convidou: 'Melissa',
    obs: 'Triatleta parceira',
    classificacao: 'parceiro',
  },
  CEEI: {
    nome: 'Ana Paula',
    cidade: 'Cabo Frio',
    celular: 22992555524,
    quem_convidou: 'Melissa',
    obs: 'Ex InterTV',
    classificacao: 'influencer',
  },
  ROPH: {
    nome: 'Catarina Lattanzi',
    cidade: 'Cabo Frio',
    celular: 22999615789,
    quem_convidou: 'Melissa',
    obs: 'Dona da principal agência da cidade',
    classificacao: 'influencer',
  },
  YNDZ: {
    nome: 'Rodrigo Felício',
    cidade: 'Cabo Frio',
    celular: 22998075620,
    quem_convidou: 'Melissa',
    obs: 'InterTV ',
    classificacao: 'Fornecedor ',
  },
  VFSS: {
    nome: 'Adriano',
    cidade: 'Nova Friburgo',
    celular: 22988025169,
    quem_convidou: 'Melissa',
    obs: 'InterTV ',
    classificacao: 'Fornecedor',
  },
  EMBF: {
    nome: 'Luize Cristine',
    cidade: 'Cabo Frio',
    celular: 22992350493,
    quem_convidou: 'Melissa',
    obs: 'Gerente de MKT Shopping Park Lagos',
    classificacao: 'Fornecedor',
  },
  UZZP: {
    nome: 'Eduardo',
    cidade: 'Araruama',
    celular: 22998233918,
    quem_convidou: 'Melissa',
    obs: 'Vendedor frela Toyoserra',
    classificacao: 'parceiro',
  },
  DDNO: {
    nome: 'Pablo ',
    cidade: 'Araruama',
    celular: 22988343121,
    quem_convidou: 'Márcio',
    obs: 'cliente promotor',
    classificacao: 'cliente',
  },
  PSOB: {
    nome: 'Rodrigo Terra',
    cidade: 'Araruama',
    celular: 22999056450,
    quem_convidou: 'Márcio',
    obs: 'cliente  ',
    classificacao: 'cliente',
  },
  ZHEI: {
    nome: 'João Junior',
    cidade: 'Cabo Frio',
    celular: 22998335671,
    quem_convidou: 'Márcio',
    obs: 'cliente e fornecedor',
    classificacao: 'cliente',
  },
  PKYH: {
    nome: 'Fábio',
    cidade: 'São Pedro da Aldeia',
    celular: 22974025152,
    quem_convidou: 'Márcio',
    obs: 'Prefeito do São Pedro da Aldeia',
    classificacao: 'autoridade municipal',
  },
  WRLN: {
    nome: 'Thiago Ribeiro',
    cidade: 'São Pedro da Aldeia',
    celular: 22974015855,
    quem_convidou: 'Márcio',
    obs: 'Secretário de Agricultura SPA',
    classificacao: 'autoridade municipal',
  },
  IBJY: {
    nome: 'Armando Cili',
    cidade: 'Sorocaba',
    celular: 11995656811,
    quem_convidou: 'Márcio',
    obs: 'Gerente Regional PV TDB',
    classificacao: 'toyota',
  },
  UWPU: {
    nome: 'Cristiano Almeida',
    cidade: 'Rio de Janeiro',
    celular: 21971259747,
    quem_convidou: 'Márcio',
    obs: 'Consultor regional PV TDB',
    classificacao: 'toyota',
  },
  HJPW: {
    nome: 'Raphael Duarte',
    cidade: 'Rio de Janeiro',
    celular: 21993155103,
    quem_convidou: 'Márcio',
    obs: 'Consultor regional Vendas TDB',
    classificacao: 'toyota',
  },
  VVVS: {
    nome: 'Thiago Cruz',
    cidade: 'Sorocaba',
    celular: 15996164663,
    quem_convidou: 'Márcio',
    obs: 'Consultor regional Vendas Diretas TDB',
    classificacao: 'toyota',
  },
  LYNB: {
    nome: 'Márcio Takeda',
    cidade: 'Sorocaba',
    celular: 11996158861,
    quem_convidou: 'Márcio',
    obs: 'DRD Toyotda',
    classificacao: 'toyota',
  },
  MHKP: {
    nome: 'Jacob',
    cidade: 'Rio de Janeiro',
    celular: 21979550451,
    quem_convidou: 'Márcio',
    obs: 'fornecedor parceiro',
    classificacao: 'fornecedor',
  },
  ZZXS: {
    nome: 'Big Ronald',
    cidade: 'Rio de Janeiro',
    celular: 21987673342,
    quem_convidou: 'Márcio',
    obs: 'fornecedor parceiro',
    classificacao: 'fornecedor',
  },
  CLKB: {
    nome: 'Jean',
    cidade: 'rio de Janeiro',
    celular: 21996411490,
    quem_convidou: 'Márcio',
    obs: 'Consultor Regional Banco Toyota',
    classificacao: 'toyota',
  },
  QXUU: {
    nome: 'Jorge Magalhães',
    cidade: 'Araruama',
    celular: 22981676737,
    quem_convidou: 'Márcio',
    obs: 'Cliente',
    classificacao: 'cliente',
  },
  EUZV: {
    nome: 'Bruno Boutique',
    cidade: 'Araruama',
    celular: 22988368363,
    quem_convidou: 'Márcio',
    obs: 'Revendedor parceiro',
    classificacao: 'revendedor',
  },
  TDAQ: {
    nome: 'Davidson Lotuscar',
    cidade: 'Araruama',
    celular: 22974037325,
    quem_convidou: 'Márcio',
    obs: 'revendedor parceiro',
    classificacao: 'revendedor',
  },
  YQUP: {
    nome: 'Thiago Arantes',
    cidade: 'Cabo Frio',
    celular: 22998222270,
    quem_convidou: 'Márcio',
    obs: 'fornecedor parceiro',
    classificacao: 'fornecedor',
  },
  WLKN: {
    nome: 'Jocimara Gama',
    cidade: 'São Paulo',
    celular: 119984194199,
    quem_convidou: 'Márcio',
    obs: 'fornecedor parceiro',
    classificacao: 'fornecedor',
  },
  KTMC: {
    nome: 'Alexandre Siciliano',
    cidade: 'Cabo Frio',
    celular: '21-985680447',
    quem_convidou: 'Erthal',
    obs: 'cliente antigo e fiel desde a VIP',
    classificacao: 'cliente',
  },
  VCTT: {
    nome: 'Amaury',
    cidade: 'Cabo Frio',
    celular: '22-988125888',
    quem_convidou: 'Erthal',
    obs: 'cliente influente',
    classificacao: 'cliente',
  },
  EQKR: {
    nome: 'Amélia',
    cidade: 'Cabo Frio',
    celular: '22-999728681',
    quem_convidou: 'Erthal',
    obs: 'dona do imóvel da VIP - e continua nossa cliente',
    classificacao: 'cliente',
  },
  HSVF: {
    nome: 'Chumbinho',
    cidade: 'São Pedro da Aldeia',
    celular: '22-999704747',
    quem_convidou: 'Erthal',
    obs: 'ex prefeito de SPA',
    classificacao: 'cliente',
  },
  GZRG: {
    nome: 'Diogo',
    cidade: 'São pedro da Aldeia',
    celular: '22-988365044',
    quem_convidou: 'Erthal',
    obs: 'revendedor parceiro',
    classificacao: 'revendedor',
  },
  JCYC: {
    nome: 'Paulinho Fricarnes',
    cidade: 'Cabo Frio',
    celular: '22-999919602',
    quem_convidou: 'Erthal',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  ILCT: {
    nome: 'Rodrigo Tomé',
    cidade: 'Cabo Frio',
    celular: '22-999113636',
    quem_convidou: 'Erthal',
    obs: 'cliente amigo',
    classificacao: 'fornecedor',
  },
  DJFR: {
    nome: 'Thiago',
    cidade: 'Cabo Frio',
    celular: '22-999823270',
    quem_convidou: 'Erthal',
    obs: 'cliente',
    classificacao: 'influencer',
  },
  CXVE: {
    nome: 'Valdemir Mendes',
    cidade: 'Cabo Frio',
    celular: '22-999717372',
    quem_convidou: 'Erthal',
    obs: 'cliente - dono do Cabofriense e da Casa do Pedreiro',
    classificacao: 'cliente',
  },
  XRQE: {
    nome: 'Wagner',
    cidade: 'Cabo Frio',
    celular: '22-981265357',
    quem_convidou: 'Erthal',
    obs: 'dono das lojas Fly - preside o movimento do comércio',
    classificacao: 'influencer',
  },
  SNPP: {
    nome: 'Edson Vidal',
    cidade: 'Cabo Frio',
    celular: '22-998835105',
    quem_convidou: 'Erthal',
    obs: 'cliente antigo desde a VIP - com relacionamento ',
    classificacao: 'cliente',
  },
  OOVS: {
    nome: 'Ivair Terra',
    cidade: 'Cabo Frio',
    celular: '22-988025364',
    quem_convidou: 'Erthal',
    obs: 'cliente antigo desde a VIP - com relacionamento ',
    classificacao: 'cliente',
  },
  BTHS: {
    nome: 'Janio Mendes',
    cidade: 'Cabo Frio',
    celular: '22-998961266',
    quem_convidou: 'Erthal',
    obs: 'foi deputado estadual, secretário de saúde hoje em CF',
    classificacao: 'influencer',
  },
  SYRW: {
    nome: 'Pedro Lima',
    cidade: 'Cabo Frio',
    celular: '22-999726000',
    quem_convidou: 'Erthal',
    obs: 'cliente, desde a VIPdono do mercado Tropical',
    classificacao: 'cliente',
  },
  AGGU: {
    nome: 'Renato Vianna',
    cidade: 'Arraial do Cabo',
    celular: '22-981208673',
    quem_convidou: 'Erthal',
    obs: 'cliente desde a VIP, ex prefeito de Arraial',
    classificacao: 'influencer',
  },
  IPCB: {
    nome: 'Valfrides',
    cidade: 'Cabo Frio',
    celular: '22-992067578',
    quem_convidou: 'Erthal',
    obs: 'cliente, dono do mercado Econômico',
    classificacao: 'influencer',
  },
  BEBB: {
    nome: 'Tenente Amanda',
    cidade: 'São pedro da Aldeia',
    celular: 21988011302,
    quem_convidou: 'Márcio',
    obs: 'Força aérea SPA',
    classificacao: 'influencer',
  },
  BWOK: {
    nome: 'Fernando Praça',
    cidade: 'São pedro da Aldeia',
    celular: 22988473159,
    quem_convidou: 'Alex',
    obs: 'relações publicas força aérea SPA',
    classificacao: 'influencer',
  },
  BPMS: {
    nome: 'Luciana',
    cidade: 'Sorocaba',
    celular: 19988696976,
    quem_convidou: 'Márcio',
    obs: 'Fundação Toyota do Brasil',
    classificacao: 'toyota',
  },
  CREV: {
    nome: 'Carlos Henrique',
    cidade: 'Saquarema',
    celular: '2297404-4003',
    quem_convidou: 'Renata',
    obs: 'Cliente SW4 e HILUX',
    classificacao: 'cliente',
  },
  BTMV: {
    nome: 'Eduardo Gonçalves',
    cidade: 'São Pedro da Aldeia',
    celular: 22988155551,
    quem_convidou: 'Renata',
    obs: 'PCD e consórcio (café)',
    classificacao: 'cliente',
  },
  LDQL: {
    nome: 'Luisa Xavier',
    cidade: 'São Pedro da Aldeia',
    celular: 22997059459,
    quem_convidou: 'Renata',
    obs: 'Cliente 03 carros (café)',
    classificacao: 'cliente',
  },
  HOXQ: {
    nome: 'Claudio Agualusa ',
    cidade: 'Armação de Buzios',
    celular: 22999768015,
    quem_convidou: 'Renata',
    obs: 'Cliente desde a VIP',
    classificacao: 'cliente',
  },
  NMJN: {
    nome: 'Sizenando',
    cidade: 'São Pedro da Aldeia',
    celular: 22999258008,
    quem_convidou: 'Renata',
    obs: 'Cliente (café)',
    classificacao: 'cliente',
  },
  NSJQ: {
    nome: 'Gabriel Grotz',
    cidade: 'Cabo Frio',
    celular: 22997719883,
    quem_convidou: 'Renata',
    obs: 'Cliente 05 carros',
    classificacao: 'cliente',
  },
  WQKL: {
    nome: 'Elias Valadão',
    cidade: 'São Pedro da Aldeia',
    celular: 22999084599,
    quem_convidou: 'Renata',
    obs: 'Cliente  03 carros',
    classificacao: 'cliente',
  },
  GFFF: {
    nome: 'Francisco Loiola',
    cidade: 'Saquarema',
    celular: 21997079330,
    quem_convidou: 'Renata',
    obs: 'Cliente 02 carros (café)',
    classificacao: 'cliente',
  },
  YFFH: {
    nome: 'Kerpson Araujo',
    cidade: 'São Pedro da Aldeia',
    celular: 22999884025,
    quem_convidou: 'Renata',
    obs: 'Cliente 03 carros',
    classificacao: 'cliente',
  },
  FSHH: {
    nome: 'Evelyn Moura',
    cidade: 'São Pedro da Aldeia',
    celular: 22999631882,
    quem_convidou: 'Renata',
    obs: 'Família cliente 06 carros, empresária',
    classificacao: 'cliente',
  },
  WRSL: {
    nome: 'Elaine Vieira',
    cidade: 'São Pedro da Aldeia',
    celular: 22998339751,
    quem_convidou: 'Renata ',
    obs: 'Influencer ',
    classificacao: 'influencer',
  },
  AYBE: {
    nome: 'Cristiane da Silva',
    cidade: 'Araruama',
    celular: 21970055701,
    quem_convidou: 'Renata',
    obs: 'Cliente carro e consórcio/empresária',
    classificacao: 'cliente',
  },
  VCWT: {
    nome: 'Cristiano',
    cidade: 'Cabo Frio',
    celular: 22998889802,
    quem_convidou: 'Renata',
    obs: 'Cliente relacionamento (café)',
    classificacao: 'cliente',
  },
  HUBC: {
    nome: 'Josmande Faria',
    cidade: 'Cabo Frio',
    celular: 22992247327,
    quem_convidou: 'Renata ',
    obs: 'Cliente relacionamento (café)',
    classificacao: 'cliente',
  },
  OARS: {
    nome: 'Junior Porto',
    cidade: 'Cabo Frio',
    celular: '22-997790777',
    quem_convidou: 'Erthal',
    obs: 'cliente PJ com frota ',
    classificacao: 'cliente',
  },
  UWVF: {
    nome: 'Silvio Martins ',
    cidade: 'Araruama',
    celular: '22 99773-3162',
    quem_convidou: 'Giovani',
    obs: 'cliente de 3 corollas e consórcio, indo pra sw4 ',
    classificacao: 'cliente ',
  },
  EYZW: {
    nome: 'Silvia',
    cidade: 'araruama',
    celular: 22999113094,
    quem_convidou: 'Giovani',
    obs: 'cliente de Yaris, perfil,insta com muitos seguidores',
    classificacao: 'cliente',
  },
  ZPQN: {
    nome: 'Adriano',
    cidade: 'saquarema',
    celular: 21970088412,
    quem_convidou: 'Giovani',
    obs: 'cliente sw4 diamond',
    classificacao: 'cliente',
  },
  ISYM: {
    nome: 'Alexsandre',
    cidade: 'araruama',
    celular: 22999523270,
    quem_convidou: 'Giovani',
    obs: 'cliente cross xrx',
    classificacao: 'cliente',
  },
  CGTA: {
    nome: 'Vanderlucio Peres',
    cidade: 'ARRAIAL DO CABO',
    celular: '22 97404-3208',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  IEXC: {
    nome: 'Eduardo Branco',
    cidade: 'cabo frio',
    celular: '22 98819-0145',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  XVNI: {
    nome: 'Julio Cesar',
    cidade: 'cabo frio',
    celular: '22 97402-6795',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  QNYV: {
    nome: 'Andre Luiz',
    cidade: 'cabo frio',
    celular: '22 98834-1466',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  FGMM: {
    nome: 'Eli Morães',
    cidade: 'cabo frio',
    celular: '22 99228-1233',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  RJYX: {
    nome: 'Karla Brandão',
    cidade: 'cabo frio',
    celular: '22-998384278',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  ZEPH: {
    nome: 'Lucierin Camargo',
    cidade: 'cabo frio',
    celular: '22-999294205',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  WWXQ: {
    nome: 'Sergio Moura',
    cidade: 'cabo frio',
    celular: '22-992524400',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  VWKG: {
    nome: 'Maicon Mbapel',
    cidade: 'cabo frio',
    celular: '22-988017562',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  SYGC: {
    nome: 'Pablo',
    cidade: 'cabo frio',
    celular: '22-988343121',
    quem_convidou: 'Giovani',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  ITOS: {
    nome: 'Léo',
    cidade: 'cabo frio',
    celular: 22998330267,
    quem_convidou: 'Márcio',
    obs: 'empresário ligado a pro lagos',
    classificacao: 'influencer',
  },
  GOII: {
    nome: 'Alex Eduardo',
    cidade: 'cabo frio',
    celular: 22999083111,
    quem_convidou: 'Márcio',
    obs: 'Pr Lagoinha cabo frio',
    classificacao: 'cliente',
  },
  XQDA: {
    nome: 'Pamela Santos Dellazei',
    cidade: 'Iguaba Grande',
    celular: 22981166426,
    quem_convidou: 'Alex',
    obs: 'Empresária Restaurante Agua na Boca ',
    classificacao: 'cliente',
  },
  ZHJG: {
    nome: 'Cícero Estevam',
    cidade: 'Cabo Frio',
    celular: 22988480964,
    quem_convidou: 'Renata',
    obs: 'cliente',
    classificacao: 'cliente',
  },
  MEJV: {
    nome: 'Felipp Rômulo',
    cidade: 'Macaé',
    celular: 22998210797,
    quem_convidou: 'Renata',
    obs: 'Empresário Macaé',
    classificacao: 'influencer',
  },
  BLJC: {
    nome: 'Fatima Castelo',
    cidade: 'Araruama',
    celular: 22988168562,
    quem_convidou: 'Márcio',
    obs: 'Empresária e advogada dona Araruama Veiculos',
    classificacao: 'revendedor',
  },
  NBBU: {
    nome: 'Daniela Bernardino',
    cidade: 'rio de Janeiro',
    celular: 21967301150,
    quem_convidou: 'Márcio',
    obs: 'fornecedor moove',
    classificacao: 'fornecedor',
  },
  IQQG: {
    nome: 'Cristiano Almeida',
    cidade: 'São Paulo',
    celular: 11950487617,
    quem_convidou: 'Márcio',
    obs: 'Consultor Regional Kinto',
    classificacao: 'toyota',
  },
  AUPM: {
    nome: 'Marcelo Mussi',
    cidade: 'Rio de Janeiro',
    celular: 22992023558,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Familia',
  },
  XSOE: {
    nome: 'Antonio Ventura',
    cidade: 'Nova Friburgo',
    celular: 22999661700,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Familia',
  },
  KRIU: {
    nome: 'Julio Catarcione',
    cidade: 'Nova Friburgo',
    celular: 22981383802,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Familia',
  },
  KTRO: {
    nome: 'Igor Gamela',
    cidade: 'Nova Friburgo',
    celular: 22992350302,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Amigo',
  },
  NISW: {
    nome: 'Luiz Bonin',
    cidade: 'Nova Friburgo',
    celular: 21983631000,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Amigo',
  },
  TMYF: {
    nome: 'Bruno Motroni',
    cidade: 'Rio de Janeiro',
    celular: 21985132057,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Amigo',
  },
  NJTS: {
    nome: 'Pedro Bueno',
    cidade: 'Nova Friburgo',
    celular: 21998597551,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Amigo',
  },
  WESV: {
    nome: 'Marcos Batista',
    cidade: 'São Paulo',
    celular: 21966594747,
    quem_convidou: 'Gustavo',
    obs: 'Cliente',
    classificacao: 'Amigo',
  },
  RYIG: {
    nome: 'Fabio Lage',
    cidade: 'São Paulo',
    celular: 19999472094,
    quem_convidou: 'Gustavo',
    obs: 'gerente nacional vendas toyota',
    classificacao: 'toyota',
  },
  NRYU: {
    nome: 'Soraya',
    cidade: 'Sorocaba',
    celular: 11981454414,
    quem_convidou: 'Gustavo',
    obs: 'chefe DRD tdb',
    classificacao: 'toyota',
  },
  WAQP: {
    nome: 'Charles Boechat',
    cidade: 'Espirito Santo',
    celular: 27999573123,
    quem_convidou: 'Gustavo',
    obs: 'gerente regional banco',
    classificacao: 'toyota',
  },
  HQIS: {
    nome: 'Fred Caldeira',
    cidade: 'Minas',
    celular: 31996587189,
    quem_convidou: 'Gustavo',
    obs: 'Gerente regional vendas',
    classificacao: 'toyota',
  },
  SKRU: {
    nome: 'Dante',
    cidade: 'Sorocaba',
    celular: 15996864716,
    quem_convidou: 'Márcio',
    obs: 'Gerente Nacional vendas diretas',
    classificacao: 'toyota',
  },
  LYIG: {
    nome: 'Agnelo Mol',
    cidade: 'São Pedro da Aldeia',
    celular: 22981402244,
    quem_convidou: 'Márcio',
    obs: 'cliente influente',
    classificacao: 'cliente',
  },
  BPEB: {
    nome: 'Ricardo Cruz',
    cidade: 'São Paulo',
    celular: 1198640969,
    quem_convidou: 'Márcio',
    obs: 'fornecedor parceiro',
    classificacao: 'fornecedor',
  },
  ABPY: {
    nome: 'Jose Ricardo',
    cidade: 'Sorocaba',
    celular: 11999351232,
    quem_convidou: 'Gustavo',
    obs: 'Diretor tdb',
    classificacao: 'Especial',
  },
  PBNO: {
    nome: 'Rafael',
    cidade: 'NaN',
    celular: 'NaN',
    quem_convidou: 'Especial',
    obs: 'Especial',
    classificacao: 'Especial',
  },

  RJKL: {
    nome: 'Masahiro',
    cidade: 'NaN',
    celular: 'NaN',
    quem_convidou: 'Especial',
    obs: 'Especial',
    classificacao: 'Especial',
  },
  QWTP: {
    nome: 'Luciano Savoldi',
    cidade: 'NaN',
    celular: 'NaN',
    quem_convidou: 'Especial',
    obs: 'Especial',
    classificacao: 'Especial',
  },
  NXYB: {
    nome: 'Pedro Dabbur',
    cidade: 'NaN',
    celular: 'NaN',
    quem_convidou: 'Especial',
    obs: 'Especial',
    classificacao: 'Especial',
  },
  HZMF: {
    nome: 'Venicio Carvalho',
    cidade: 'NaN',
    celular: 'NaN',
    quem_convidou: 'Especial',
    obs: 'Especial',
    classificacao: 'Especial',
  },

  TUTO: {
    nome: 'João Pedro',
    cidade: 'Nova Friburgo',
    celular: 22998961154,
    quem_convidou: 'Controle',
    obs: 'Controle',
    classificacao: 'Controle',
  },
  QWBK: {
    nome: 'Melissa',
    cidade: 'Nova Friburgo',
    celular: 22988199929,
    quem_convidou: 'Controle',
    obs: 'Controle',
    classificacao: 'Controle',
  },
  AXYQ: {
    nome: 'Marcio',
    cidade: 'Nova Friburgo',
    celular: 22981259416,
    quem_convidou: 'Controle',
    obs: 'Controle',
    classificacao: 'Controle',
  },
  // nova lista

  HNLW: {
    nome: 'Joilson Wemelinger',
    cidade: 'NaN',
    celular: 5522992318377,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  GPHL: {
    nome: 'Eduardo Godoy',
    cidade: 'NaN',
    celular: 5522999623083,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  NYFM: {
    nome: 'Cesar Romero Spinelli',
    cidade: 'NaN',
    celular: 5522981268366,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  YYMZ: {
    nome: 'Romulo Spinelli',
    cidade: 'NaN',
    celular: 5522988121634,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  PCIU: {
    nome: 'Joao Baptista Spinelli',
    cidade: 'NaN',
    celular: 5522999618430,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  IQEY: {
    nome: 'Carlos Alberto',
    cidade: 'NaN',
    celular: 5522999617334,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  LSKO: {
    nome: 'James',
    cidade: 'NaN',
    celular: 5521995315401,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  TLAV: {
    nome: 'Fabio Lancelott',
    cidade: 'NaN',
    celular: 5532984248380,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  QPJH: {
    nome: 'Douglas Melo',
    cidade: 'NaN',
    celular: 5521976751332,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  MOWU: {
    nome: 'Amaury Alexandre',
    cidade: 'NaN',
    celular: 5521988670267,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  XAMQ: {
    nome: 'Edmar',
    cidade: 'NaN',
    celular: 5521967379994,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  BJMQ: {
    nome: 'Vitor',
    cidade: 'NaN',
    celular: 5522997598485,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  CDTC: {
    nome: 'Joel Wermelinger',
    cidade: 'NaN',
    celular: 5522992317638,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  JHUB: {
    nome: 'Jairo Wermelinger',
    cidade: 'NaN',
    celular: 5522999617498,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  NMXO: {
    nome: 'Roosevelt',
    cidade: 'NaN',
    celular: 5522981082136,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  NEXD: {
    nome: 'Celso',
    cidade: 'NaN',
    celular: 5522999414111,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  KLXL: {
    nome: 'Osvaldo',
    cidade: 'NaN',
    celular: 5522999611258,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  JXOY: {
    nome: 'Alexandre Bianchini',
    cidade: 'NaN',
    celular: 5519998042833,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  DOGX: {
    nome: 'João Luis',
    cidade: 'NaN',
    celular: 5521996996913,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  EOAZ: {
    nome: 'Marcio',
    cidade: 'NaN',
    celular: 5524992583489,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  PMDE: {
    nome: 'Julia',
    cidade: 'NaN',
    celular: 5522999996094,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  MZMR: {
    nome: 'Luis Fernando',
    cidade: 'NaN',
    celular: 5524992110702,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  GKKN: {
    nome: 'Silvia Guedon',
    cidade: 'NaN',
    celular: 5524988035963,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  MTJI: {
    nome: 'Jose Alexandre',
    cidade: 'NaN',
    celular: 5522999484724,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  QMLH: {
    nome: 'Braulio',
    cidade: 'NaN',
    celular: 5522999991240,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  HVGS: {
    nome: 'Marcia Carestiato',
    cidade: 'NaN',
    celular: 5522999997013,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  ARBT: {
    nome: 'Adriana Ventura',
    cidade: 'NaN',
    celular: 5522992447183,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  HZGA: {
    nome: 'Conte Bittencourt',
    cidade: 'NaN',
    celular: 5521999827234,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  OKBV: {
    nome: 'Paulo Bruno',
    cidade: 'NaN',
    celular: 5521973053939,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  IUFZ: {
    nome: 'Sabrina Celles',
    cidade: 'NaN',
    celular: 5522988579232,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  WOOC: {
    nome: 'Pio Sabrina Celles',
    cidade: 'NaN',
    celular: 5522981413292,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  LJCM: {
    nome: 'Alexandre Cordeiro',
    cidade: 'NaN',
    celular: 5521979184200,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  EXRA: {
    nome: 'Geraldo',
    cidade: 'NaN',
    celular: 5522998129113,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AZCQ: {
    nome: 'Ramon Gonçalves',
    cidade: 'NaN',
    celular: 5521983290230,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  ULJC: {
    nome: 'Sylvestre',
    cidade: 'NaN',
    celular: 5521979310008,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  IGMM: {
    nome: 'Paulo',
    cidade: 'NaN',
    celular: 5521988747721,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  XRPX: {
    nome: 'Rosangela',
    cidade: 'NaN',
    celular: 5521988747617,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  ACBD: {
    nome: 'Luciano Giacomel',
    cidade: 'NaN',
    celular: 5521971790110,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },

  //parte 3...
  LQLL: {
    nome: 'Elvis Lopes',
    cidade: 'NaN',
    celular: 5521971997787,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  YJSB: {
    nome: 'Almir Queiroz',
    cidade: 'NaN',
    celular: 552499812482,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  UUWD: {
    nome: 'Valdecyr Souza',
    cidade: 'NaN',
    celular: 5522999762309,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  VAKP: {
    nome: 'Claudia Fernandes',
    cidade: 'NaN',
    celular: 5521993236807,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  UFRM: {
    nome: 'Luiz Carlos',
    cidade: 'NaN',
    celular: 5522998911590,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  JCCT: {
    nome: 'Maria Angélica',
    cidade: 'NaN',
    celular: 552999834497,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  GJZK: {
    nome: 'Luciana Bernath',
    cidade: 'NaN',
    celular: 5522999949795,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  IMDD: {
    nome: 'Robert Luiz',
    cidade: 'NaN',
    celular: 5522999739738,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  FZCY: {
    nome: 'Alessandro Moraes',
    cidade: 'NaN',
    celular: 5522988057809,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  URNI: {
    nome: 'Luciama Portugal',
    cidade: 'NaN',
    celular: 5522997653069,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  BFRA: {
    nome: 'Renata Cristiane',
    cidade: 'NaN',
    celular: 5522999377669,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  WQJH: {
    nome: 'Milton mendes',
    cidade: 'NaN',
    celular: 5522988586977,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  TRAM: {
    nome: 'Gastão carneiro',
    cidade: 'NaN',
    celular: 5521999150712,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  DPKQ: {
    nome: 'Edson junior',
    cidade: 'NaN',
    celular: 5522999020543,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  YQFG: {
    nome: 'Maria Teresa',
    cidade: 'NaN',
    celular: 5522988572530,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  NPDZ: {
    nome: 'Amadeu Romão',
    cidade: 'NaN',
    celular: 5514981241624,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  WWRK: {
    nome: 'Denise Garcia',
    cidade: 'NaN',
    celular: 552292557162,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  ERBB: {
    nome: 'Carlos jose',
    cidade: 'NaN',
    celular: 5522988378206,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  NRXK: {
    nome: 'Patrícia Duarte',
    cidade: 'NaN',
    celular: 5522999675861,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  TBDX: {
    nome: 'Inea',
    cidade: 'NaN',
    celular: 5522999397014,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  VSNF: {
    nome: 'Fernando Cesar',
    cidade: 'NaN',
    celular: 5522999397014,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  XPAK: {
    nome: 'Elvis Lopes',
    cidade: 'NaN',
    celular: 5521971997787,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  ZUDP: {
    nome: 'Leonardo Sabord',
    cidade: 'NaN',
    celular: 5522998133422,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  KNJR: {
    nome: 'Almir Queiroz',
    cidade: 'NaN',
    celular: 5524998182482,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  KOYG: {
    nome: 'Carolos',
    cidade: 'NaN',
    celular: 5522999778240,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  WFPF: {
    nome: 'Valdecyr Souza',
    cidade: 'NaN',
    celular: 5522999762309,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  WCPL: {
    nome: 'Felipe Pimentel',
    cidade: 'NaN',
    celular: 5521975411583,
    quem_convidou: 'NaN',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AASC: {
    nome: 'Lindomar',
    cidade: 'NaN',
    celular: 5511999752005,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAZC: {
    nome: 'Walter Oliveira',
    cidade: 'NaN',
    celular: 5522997050354,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAZI: {
    nome: 'Lucas',
    cidade: 'NaN',
    celular: 5522981270097,
    quem_convidou: 'Fabiano',
    obs: 'Tavares Garcia',
    classificacao: 'NaN',
  },
  AAZH: {
    nome: 'Rafael',
    cidade: 'NaN',
    celular: 5522981189832,
    quem_convidou: 'Fabiano',
    obs: 'Tavares Garcia',
    classificacao: 'NaN',
  },
  AAWG: {
    nome: 'Guilherme',
    cidade: 'NaN',
    celular: 5522988124688,
    quem_convidou: 'Giovani',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWF: {
    nome: 'Edilan',
    cidade: 'NaN',
    celular: 5522988057035,
    quem_convidou: 'Julio',
    obs: 'Contar',
    classificacao: 'NaN',
  },
  AAWE: {
    nome: 'Edson Mussi',
    cidade: 'NaN',
    celular: 5522999611686,
    quem_convidou: 'Julio',
    obs: 'Gigalink',
    classificacao: 'NaN',
  },
  AAWD: {
    nome: 'Salvador Neto',
    cidade: 'NaN',
    celular: 5522999402010,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  // Mais convidados
  AAWJ: {
    nome: 'Sidnei Warol',
    cidade: 'NaN',
    celular: 5522997875330,
    quem_convidou: 'Márcio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWK: {
    nome: 'Romulo Werneck',
    cidade: 'NaN',
    celular: 5522981220407,
    quem_convidou: 'Márcio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWL: {
    nome: 'Carlos André',
    cidade: 'NaN',
    celular: 5522999950228,
    quem_convidou: 'Márcio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWM: {
    nome: 'Fabio Junior',
    cidade: 'NaN',
    celular: 5522988757425,
    quem_convidou: 'Márcio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWN: {
    nome: 'Sra Christiane',
    cidade: 'NaN',
    celular: 5522999110905,
    quem_convidou: 'Márcio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  // Adicional
  AAWO: {
    nome: 'Luciano Motta',
    cidade: 'NaN',
    celular: 5522998024420,
    quem_convidou: 'Melissa',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWP: {
    nome: 'Nathalia Teixeira',
    cidade: 'NaN',
    celular: 5522981795894,
    quem_convidou: 'Melissa',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWQ: {
    nome: 'Mariana',
    cidade: 'NaN',
    celular: 5522988574464,
    quem_convidou: 'Melissa',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWR: {
    nome: 'Karen Givigi',
    cidade: 'NaN',
    celular: 5522991059678,
    quem_convidou: 'Melissa',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  // mais convites
  AAWT: {
    nome: 'Gelcimar',
    cidade: 'NaN',
    celular: 5522997742645,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWU: {
    nome: 'Fernando',
    cidade: 'NaN',
    celular: 5521998309015,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWV: {
    nome: 'Cornélio',
    cidade: 'NaN',
    celular: 5521999825359,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWX: {
    nome: 'Sr. Aguinaldo',
    cidade: 'NaN',
    celular: 5522981402233,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWW: {
    nome: 'Hugo',
    cidade: 'NaN',
    celular: 5522999714000,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWY: {
    nome: 'Zezeco',
    cidade: 'NaN',
    celular: 5522988371240,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAWZ: {
    nome: 'Mauricio',
    cidade: 'NaN',
    celular: 5522997218582,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYA: {
    nome: 'Paulo',
    cidade: 'NaN',
    celular: 5522999755566,
    quem_convidou: 'Júlio - Prefeito Fábio SPA',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYB: {
    nome: 'João',
    cidade: 'NaN',
    celular: 5522988291842,
    quem_convidou: 'Márcio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  // mais convites
  AAYC: {
    nome: 'Rafael Spinelli',
    cidade: 'NaN',
    celular: 5521998576522,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYD: {
    nome: 'Eduardo Jacome',
    cidade: 'NaN',
    celular: 5521998156784,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYE: {
    nome: 'Eneas Jacome',
    cidade: 'NaN',
    celular: 5521983027408,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYF: {
    nome: 'Guto',
    cidade: 'NaN',
    celular: 5522992318370,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  // ainda mais convites
  AAYG: {
    nome: 'Edson',
    cidade: 'NaN',
    celular: 5522999473596,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYH: {
    nome: 'Vantoil',
    cidade: 'NaN',
    celular: 5522998956475,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYI: {
    nome: 'Maximino',
    cidade: 'NaN',
    celular: 5522997351134,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYJ: {
    nome: 'Alexandre',
    cidade: 'NaN',
    celular: 5522997214590,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYK: {
    nome: 'Paulo Cesar',
    cidade: 'NaN',
    celular: 5521972333227,
    quem_convidou: 'Gustavo',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYL: {
    nome: 'Silvia',
    cidade: 'NaN',
    celular: 5522999464699,
    quem_convidou: 'Gustavo',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYM: {
    nome: 'Paulo Cesar',
    cidade: 'NaN',
    celular: 5521997974796,
    quem_convidou: 'Gustavo',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYN: {
    nome: 'Rui Guimarães',
    cidade: 'NaN',
    celular: 5522997178050,
    quem_convidou: 'Guilherme',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYO: {
    nome: 'Rodrigo Guimarães',
    cidade: 'NaN',
    celular: 5522992835508,
    quem_convidou: 'Guilherme',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYP: {
    nome: 'Nadia Agostini',
    cidade: 'NaN',
    celular: 5522988268464,
    quem_convidou: 'Renata',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYQ: {
    nome: 'Eduardo Jacome',
    cidade: 'NaN',
    celular: 5522988010013,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYR: {
    nome: 'Vera Jacome',
    cidade: 'NaN',
    celular: 5521994109340,
    quem_convidou: 'Julio',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYS: {
    nome: 'Daniel Peralta',
    cidade: 'NaN',
    celular: 5522988144292,
    quem_convidou: 'Guilherme',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYT: {
    nome: 'Danilo Azevedo',
    cidade: 'NaN',
    celular: 5522997580617,
    quem_convidou: 'Melissa',
    obs: 'NaN',
    classificacao: 'NaN',
  },
  AAYU: {
    nome: 'José Izai',
    cidade: 'NaN',
    celular: 552198626768,
    quem_convidou: 'Julio',
    obs: 'Comprou o primeiro Corolla da Toyoserra',
    classificacao: 'NaN',
  },
  AAYV: {
    nome: 'Adalto',
    cidade: 'NaN',
    celular: 5522998545656,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAYX: {
    nome: 'Geraldo',
    cidade: 'NaN',
    celular: 5522998129113,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAYW: {
    nome: 'Barbara',
    cidade: 'NaN',
    celular: 5527999871478,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAYY: {
    nome: 'João',
    cidade: 'NaN',
    celular: 5522998113155,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAYZ: {
    nome: 'Rita',
    cidade: 'NaN',
    celular: 5522998134820,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAZA: {
    nome: 'Valdir',
    cidade: 'NaN',
    celular: 5522999843442,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAZB: {
    nome: 'Julio',
    cidade: 'NaN',
    celular: 5522981259422,
    quem_convidou: 'JP',
    obs: '',
    classificacao: 'NaN',
  },
  AAZC: {
    nome: 'Dr. Francisco Neto',
    cidade: 'NaN',
    celular: 5522988130091,
    quem_convidou: 'Bruno Hermann',
    obs: '',
    classificacao: 'NaN',
  },
  AAZD: {
    nome: 'Cristiano',
    cidade: 'NaN',
    celular: 5521996556016,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
  AAZE: {
    nome: 'Valnes',
    cidade: 'NaN',
    celular: 5522996070716,
    quem_convidou: 'Marcio',
    obs: '',
    classificacao: 'NaN',
  },
}
